sudo: required
dist: trusty
language: node_js
node_js:
  - "4"
  - "6"
  - "7"
  - "8"

after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'

install:
  - npm install

before_script:
  - ./scripts/start-server.sh

script: make tests

after_script:
  - ./scripts/stop-server.sh
  - kill -9 `cat pid.txt`
